// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import 'quasar/dist/types/feature-flag';

// eslint-disable
declare module 'quasar/dist/types/feature-flag' {
  interface QuasarFeatureFlags {
    store: true;
  }
}
