export const ERC_APPROVAL_SIGNATURE = '0x8c5be1e5';
export const ERC_APPROVAL_ALL_SIGNATURE = '0x17307eab';
export const APPROVAL_SIGNATURES = [
    ERC_APPROVAL_SIGNATURE, ERC_APPROVAL_ALL_SIGNATURE,
];
